### ISSUE TITLE
I'm eligible for GitHub developers but I didn't get the air drop.

### ISSUE THREAD

**Issue by NickCodeJourney** [keep-starknet-strange/awesome-starknet#74]
![image](https://github.com/keep-starknet-strange/awesome-starknet/assets/72905543/3f56bc1d-b78e-408b-b294-a0df97df5c6a)
![image](https://github.com/keep-starknet-strange/awesome-starknet/assets/72905543/dcfe2ed6-0966-464c-9da9-6d554dcb1a95)

**Comment by NickCodeJourney** [comment]
please help me

**Comment by Asthestarsfalll** [comment]
encounter the same situation

**Comment by echo-hhj** [comment]
me too
![pEcWD76GqI](https://github.com/keep-starknet-strange/awesome-starknet/assets/50286010/cf293d55-c21e-40bd-b8c9-8ab54eda9b8f)

**Comment by iqinning** [comment]
please help me , I have 4 commits  but 0 air drop. @gakonst 

<img width="2553" alt="image" src="https://github.com/keep-starknet-strange/awesome-starknet/assets/18241433/e0c28d54-f0d4-4de4-b611-2c0a28e045bc">
<img width="2536" alt="image" src="https://github.com/keep-starknet-strange/awesome-starknet/assets/18241433/e59e226b-70ae-4d51-9a13-349a03af61e1">
<img width="2556" alt="image" src="https://github.com/keep-starknet-strange/awesome-starknet/assets/18241433/36fd17f3-4bbc-4afc-9bd1-8bd4ff8fcdc3">

**Comment by programmerwy** [comment]
Same here. I made 2 commits to a 10K+ stars [repository](https://github.com/alibaba/formily) between Feb and May 2022, but no air drop
![image](https://github.com/keep-starknet-strange/awesome-starknet/assets/24842116/ff4f4e77-56e6-4c2d-bac4-b935dc088db9)

**Comment by 842000** [comment]
I came for the airdrop

**Comment by screetBloom** [comment]
Same here，I've submitted FEATURES to a lot of projects over 10k Star（Vue CLI 29.8k star、esbuild 36.8k star）

like the screenshot below

<img width="1022" alt="image" src="https://github.com/keep-starknet-strange/awesome-starknet/assets/22092110/62861103-af60-4c2c-8a74-81be6b027043">

**Comment by Max10240** [comment]
same to me :(
username: `Max10240`
[PR for ts-eslint](https://github.com/typescript-eslint/typescript-eslint/pull/7161/commits)
[PR for stylelint](https://github.com/stylelint/stylelint/pull/6861/commits)

**Comment by screetBloom** [comment]
cc @gakonst @AbdelStark

Can someone please fix this?

**Comment by smallzhongfeng** [comment]
The world is always unfair. I hope that by accumulating this bad luck, I can welcome more good luck, friends.

**Comment by alula** [comment]
I also seem "ineligible"

**Comment by Giri-Aayush** [comment]
This repository is for Starknet ecosystem resources and documentation. For airdrop eligibility issues, please contact the maintainers of the projects you contributed to directly. We're not involved in airdrop distribution decisions. Closing this issue as it's out of scope for this project.
