### ISSUE TITLE
Unable to claim tokens 

### ISSUE THREAD

**Issue by IamFosterAlex** [keep-starknet-strange/awesome-starknet#75]
Fortunately for me I'm eligible for the airdrop but unfortunately upto this day I've not been able to claim the airdrop token. I'm always faced with the error *network is busy please come back later*😞😞

**Comment by GitMensch** [comment]
Is there a way to stay informed on a new round without using X/Twitter? A GH issue like this to subscribe to would be useful.

**Comment by Giri-Aayush** [comment]
This repository is for Starknet resources and documentation. For airdrop eligibility issues, please contact the maintainers of the projects you contributed to directly. We're not involved in airdrop distribution decisions. Closing this issue as it's out of scope for this project.
