### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by iamashwin99** [keep-starknet-strange/awesome-starknet#81]
List of broken links:

- https://github.com/keep-starknet-strange/awesome-starknet/blob/a0c86399372ce8cb46881f9b9297aa6ae3387711/README.md?plain=1#L77
- https://github.com/keep-starknet-strange/awesome-starknet/blob/a0c86399372ce8cb46881f9b9297aa6ae3387711/README.md?plain=1#L76

We could consider adding a CI to test broken links.

**Comment by Giri-Aayush** [comment]
Closing this issue as it duplicates #91, which already has a submitted PR to update the Cairo Documentation link and resolve the 404 error.
