### ISSUE TITLE
Decompilers

### ISSUE THREAD

**Issue by kristiann57** [keep-starknet-strange/awesome-starknet#82]
Hi, thanks for putting all these resources together. 

Do you know if there is any good way to decompile SIerra bytecode back to Cairo 1??

thank you

**Comment by Giri-Aayush** [comment]
There's this cool tool called [Thoth](https://github.com/FuzzingLabs/thoth) that might be just what you're looking for. It's a security toolkit for Cairo/Starknet that includes a decompiler, among other awesome features like analyzers and disassemblers.

It can do a bunch of neat stuff like generating call graphs, control-flow graphs, and even has a symbolic execution engine.
I'm going to close this issue, but don't worry - will create a new issue to add Thoth to our repo's resource list. That way, everyone can easily find it in the future.
